plugins {
	id 'java-library'
	id 'eclipse'
	id 'idea'
	id 'fabric-loom' version '1.10-SNAPSHOT'
	id 'org.jetbrains.gradle.plugin.idea-ext' version "1.1.10"
	id 'maven-publish'
	// Version List: https://projects.neoforged.net/neoforged/ModDevGradle
	id "com.dorongold.task-tree" version "4.0.0"
	id 'com.gradleup.shadow' version '8.3.3'
}

configurations {
	shade
}

shadowJar {
	dependsOn(tasks.named("jar"))
	afterEvaluate {
		from({ tasks.named("jar").get().outputs })
	}
	archiveClassifier.set('universal')
	configurations = [project.configurations.shade]
}

jar {
	archiveClassifier = "slim"
}

def secrets = new Properties()
def secretsFile = file('secrets.properties')
if (secretsFile.exists()) {
	secretsFile.withInputStream {
		stream -> secrets.load(stream)
	}

	fileTree("secrets").matching {
		include "**/*.properties"
	}.each {
		File file ->
			file.withInputStream {
				stream -> secrets.load(stream)
			}
	}
}

idea {
	project.settings.compiler.javac {
		// Disable “Report use of deprecated features” https://github.com/JetBrains/gradle-idea-ext-plugin/wiki#javac-settings-of-idea-compiler
		generateDeprecationWarnings = false
	}

	module {
		downloadJavadoc = true
		downloadSources = true
	}
}

version = (hasProperty("CIRevision") ? CIRevision : project.mod_version)
group = group_name

java {
	toolchain {
		languageVersion.set(JavaLanguageVersion.of(21))
	}
}

tasks.withType(JavaCompile).configureEach {
	//options.compilerArgs << "-Xlint:all,-classfile,-processing,-deprecation,-this-escape" << "-Werror"
	options.encoding = 'UTF-8'
}

base {
	archivesName = "${project.mod_id}-${project.minecraft_version}"
}

subprojects {
	version = project(":").version
}

fabricApi {
	configureDataGeneration()
}

loom {
	accessWidenerPath.set(file("src/main/resources/twilightforest.accesswidener"))

	runs {
		data {
			client()

			name "Data Generation"
			vmArg "-Dfabric-api.datagen"
			vmArg "-Dfabric-api.datagen.output-dir=${file("src/main/generated")}"
			vmArg "-Dfabric-api.datagen.modid=twilightforest"
			vmArg "-Dmixin.debug.export=true"

			// Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
			vmArg "-Dporting_lib.datagen.existing_resources=${file('src/main/resources/').getAbsolutePath()}"
		}
	}

}

jar {
	exclude 'data/twilightforest/function/**'
}

sourceSets.main.resources { srcDir 'src/main/generated' }

repositories {
	mavenLocal()
	maven {
		name 'Jared\'s Maven' // JEI
		url 'https://maven.blamejared.com/'
	}
	maven {
		name = "OctoStudios" //Curios
		url = uri("https://maven.octo-studios.com/releases")
	}
	maven {
		name 'Shedaniel\'s Maven' //REI
		url "https://maven.shedaniel.me"
	}
	maven {
		name = "TerraformersMC" //EMI
		url = "https://maven.terraformersmc.com/"
	}
	maven { // TOP
		url "https://maven.k-4u.nl"
	}
	maven { //CS
		url "https://nexus.resourcefulbees.com/repository/maven-public/"
	}
    maven {
        name 'Curseforge Maven' // Jade
        url "https://www.cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
	maven {
		name 'Tama\'s Maven' // Beanification
		url 'https://maven.tamaized.com/releases/'
		content {
			includeGroup("tamaized")
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				name = "Modrinth"
				url = "https://api.modrinth.com/maven"
			}
		}
		filter {
			includeGroup "maven.modrinth"
		}
	}
	maven {
		name = "Fuzs Mod Resources"
		url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/"
	}

	maven {
		name = "TerraformersMC"
		url = "https://maven.terraformersmc.com/"
	}
	maven {
		name = "Illusive Soulworks maven"
		url = "https://maven.theillusivec4.top/"
	}
	maven { url "https://maven.architectury.dev/" }
	maven {
		name = "TerraformersMC"
		url = "https://maven.terraformersmc.com/"
	}
	maven {
		name = "Ladysnake Libs"
		url = 'https://maven.ladysnake.org/releases'
	}
	maven {
		name = "ParchmentMC"
		url = "https://maven.parchmentmc.org"
	}

	maven {
		name = "devOS"
		url "https://mvn.devos.one/releases/"
	}

	maven {
		name = "devOS (Snapshots)"
		url "https://mvn.devos.one/snapshots/"
	}

	maven {
		name = "JitPack"
		url "https://jitpack.io/"
	}

	maven {
		name = "MinecraftForge"
		url "https://maven.minecraftforge.net/"
	}

	maven {
		name = "Cafeteria Dev"
		url "https://maven.cafeteria.dev/releases/"
	}

	maven {
		name = "JamiesWhiteShirt Dev"
		url "https://maven.jamieswhiteshirt.com/libs-release"
		content {
			includeGroup("com.jamieswhiteshirt")
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.layered() {
		officialMojangMappings()
		parchment("org.parchmentmc.data:parchment-${project.minecraft_version}:${project.property("neoForge.parchment.mappingsVersion")}@zip")
	}

	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	// Fabric API. This is technically optional, but you probably want it anyway.
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

	//make sure to only pick one of these when testing (switch others to compileOnly)
	modImplementation "mezz.jei:jei-${project.base_minecraft_version}-fabric:${project.jei_version}"
	modCompileOnly "me.shedaniel:RoughlyEnoughItems-fabric:${project.rei_version}"
	modCompileOnly "dev.emi:emi-fabric:${project.emi_version}+${project.base_minecraft_version}"

	// theillusivec4
	modImplementation 'dev.emi:trinkets:3.10.0'

	modImplementation "com.terraformersmc:modmenu:11.0.3"

	//curse maven
	modImplementation "maven.modrinth:jade:15.10.1+fabric"
	modImplementation "maven.modrinth:cosmetic-armor-revitalized-fabric:1.7.0"
	//modRuntimeOnly "curse.maven:worldedit-225608:5830452"
//	runtimeOnly "curse.maven:jeed-532286:5483315"
//	runtimeOnly "curse.maven:museum-curator-859070:4629894"
	/*if (project.enable_tips_mod == 'true') {
		runtimeOnly "curse.maven:tips-306549:5844057"
		runtimeOnly "curse.maven:bookshelf-228525:6098975"
		runtimeOnly "curse.maven:prickle-1023259:5836410"
	}*/
	//runtimeOnly "curse.maven:suggestion-provider-fix-469647:5598604"

	//compileOnly "mcjty.theoneprobe:theoneprobe:${project.top_version}"

    //mods we dont have compat with but are nice to have
	modRuntimeOnly "com.telepathicgrunt:CommandStructures-Fabric:4.3.2+1.20.6"

	//testImplementation group: 'net.neoforged', name: 'testframework', version: project.neo_version
	/*testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter', version: '5.10.3'
	testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.10.3'
	testImplementation group: 'org.mockito', name: 'mockito-junit-jupiter', version: '5.12.0'*/

	modApi "fuzs.forgeconfigapiport:forgeconfigapiport-fabric:21.1.3"
	// https://mvnrepository.com/artifact/com.google.code.findbugs/jsr305
	include(implementation("com.google.code.findbugs:jsr305:3.0.2"))

	def portingLibs = [ "base", "client_events", "core", "fluids", "entity", "items", "item_abilities", "registry", "level_events", "loot", "model_loader", "models", "render_types", "resources", "transfer" ]
	for (lib in portingLibs) {
		modImplementation(include("io.github.fabricators_of_create.Porting-Lib:$lib:${property("porting_lib_version")}"))
	}
	modImplementation "dev.architectury:architectury-fabric:13.0.6"

	modApi(include("com.github.Chocohead:Fabric-ASM:v2.3"))
	api(include("net.minecraftforge:unsafe:0.2.+"))

	include(implementation(annotationProcessor("io.github.llamalad7:mixinextras-fabric:0.5.0-rc.2")))
}

/*configurations.testImplementation {
	exclude module: 'tf-asm'
}

test {
	useJUnitPlatform()
	testLogging {
		events "failed"

		showExceptions true
		exceptionFormat "full"
		showCauses true
		showStackTraces true

		showStandardStreams = false
	}
}*/

processResources {
	def ver = project.version
	filesMatching("META-INF/neoforge.mods.toml") {
		expand([
			'file'           : [
				'jarVersion': ver
			]
		])
	}
}

jar {
	manifest {
		attributes([
			'Specification-Title'     : mod_id,
			'Specification-Vendor'    : "TeamTwilight",
			'Specification-Version'   : "1",
			'Implementation-Title'    : this.project.name,
			'Implementation-Version'  : this.project.jar.archiveVersion,
			'Implementation-Vendor'   : "TeamTwilight",
			'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
		])
	}
}

def mavenUser = System.getenv("MAVEN_USER")?: secrets.getProperty("maven_username")
def mavenToken = System.getenv("MAVEN_PASS")?: secrets.getProperty("maven_password")

publishing {
	publications {
		create('mavenJava', MavenPublication) {
			afterEvaluate {
				artifact this.project.shadowJar
				artifact this.project.sourceJar
			}
			groupId mavenUser
			artifactId this.project.mod_id
		}
	}
	repositories {
		maven {
			url "https://maven.tamaized.com/releases"
			credentials {
				username mavenUser
				password mavenToken
			}
		}
	}
}

tasks.register('sourceJar', Jar) {
	dependsOn 'classes'
	from sourceSets.main.allSource
	archiveClassifier = 'sources'
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = 'UTF-8'
}

build.dependsOn shadowJar
